#
# Example docker-compose.yml to deploy evething.
#

web:
  build: evething
  ports:
    - "8080"
  environment:
    ADMIN_NAME: Administrator
    ADMIN_EMAIL: someone@somewhere.com
    SECRET_KEY: "change this"
  links:
    - db
    - mail
    - redis
    - memcached
  restart: always
db:
  image: postgres
  restart: always
lb:
  build: nginx
  ports:
    - "80:80"
  links:
    - web
  volumes_from:
    - web
  restart: always
mail:
  image: elsdoerfer/exim-sender
  dns: # Docker's DNS is not compatible with Exim
        - 8.8.8.8
        - 4.4.4.4
  environment:
    ALLOWED_HOSTS: "*"
  restart: always
redis:
  image: redis
  restart: always
memcached:
  image: sylvainlasnier/memcached
  restart: always
celery:
  image: compose_web # This is the web container's built image - depends on the directory name of docker-compose.yml
  command: celery worker -A evething -B -Q et_high,et_medium,et_low -c 2 -b redis://compose_redis_1/
  working_dir: /opt/evething
  links:
    - db
    - redis
  restart: always
# vim: set sw=2 ts=2 sts=2 expandtab:
